version: 0.2

phases:
  pre_build:
    commands:
      - echo "Preparing Lambda package for api-proxy"
      - echo "Build started on `date`"
      - mkdir -p lambda-package
      - cp src/proxy/api-proxy.mjs lambda-package/index.mjs
      - cp src/proxy/mysql-cache.mjs lambda-package/mysql-cache.mjs
      - cp src/proxy/local-cache.mjs lambda-package/local-cache.mjs
      - cp src/proxy/package.json lambda-package/package.json
      - |
        if [ -f "src/res/keys/global-bundle.pem" ]; then
          mkdir -p lambda-package/res/keys
          cp src/res/keys/global-bundle.pem lambda-package/res/keys/global-bundle.pem
          echo "Included RDS CA bundle in Lambda package"
        else
          echo "Warning: src/res/keys/global-bundle.pem not found, SSL may not work"
        fi

  build:
    commands:
      - echo "Creating Lambda deployment package"
      - chmod +x src/proxy/build-package.sh
      - ./src/proxy/build-package.sh

  post_build:
    commands:
      - echo "Deploying Lambda function api-proxy-${ENV}"
      - chmod +x src/proxy/deploy-proxy.sh
      - ./src/proxy/deploy-proxy.sh
      - echo "Deployment completed successfully"